/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Sol from "./ERC20.sol/index.js";
export * as ierc20Sol from "./IERC20.sol/index.js";
export * as extensions from "./extensions/index.js";
