/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Burnable } from "./ERC20Burnable.js";
export type { ERC20Permit } from "./ERC20Permit.js";
export type { IERC20Metadata } from "./IERC20Metadata.js";
export type { IERC20Permit } from "./IERC20Permit.js";
