/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20BurnableSol from"./ERC20Burnable.sol/index.js";
export type { erc20BurnableSol };
import type * as erc20PermitSol from"./ERC20Permit.sol/index.js";
export type { erc20PermitSol };
import type * as ierc20MetadataSol from"./IERC20Metadata.sol/index.js";
export type { ierc20MetadataSol };
import type * as ierc20PermitSol from"./IERC20Permit.sol/index.js";
export type { ierc20PermitSol };
