/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc5267Sol from"./IERC5267.sol/index.js";
export type { ierc5267Sol };
import type * as draftIerc6093Sol from"./draft-IERC6093.sol/index.js";
export type { draftIerc6093Sol };
