/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as draftIerc6093Sol from"./draft-IERC6093.sol/index.js";
export type { draftIerc6093Sol };
export type { IERC5267 } from "./IERC5267.js";
