/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ecdsaSol from"./ECDSA.sol/index.js";
export type { ecdsaSol };
import type * as eip712Sol from"./EIP712.sol/index.js";
export type { eip712Sol };
