/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20MockSol from"./ERC20Mock.sol/index.js";
export type { erc20MockSol };
import type * as opGasPriceOracleMockSol from"./OpGasPriceOracleMock.sol/index.js";
export type { opGasPriceOracleMockSol };
import type * as ownableTestSol from"./OwnableTest.sol/index.js";
export type { ownableTestSol };
