/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from"./ERC20.sol/index.js";
export type { erc20Sol };
import type * as wethSol from"./WETH.sol/index.js";
export type { wethSol };
