/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20BurnableSol from "./ERC20Burnable.sol/index.js";
export * as erc20PermitSol from "./ERC20Permit.sol/index.js";
export * as ierc20MetadataSol from "./IERC20Metadata.sol/index.js";
export * as ierc20PermitSol from "./IERC20Permit.sol/index.js";
