"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OpGasPriceOracleMock__factory = exports.ERC20Mock__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ERC20Mock__factory_1 = require("./ERC20Mock__factory");
Object.defineProperty(exports, "ERC20Mock__factory", { enumerable: true, get: function () { return ERC20Mock__factory_1.ERC20Mock__factory; } });
var OpGasPriceOracleMock__factory_1 = require("./OpGasPriceOracleMock__factory");
Object.defineProperty(exports, "OpGasPriceOracleMock__factory", { enumerable: true, get: function () { return OpGasPriceOracleMock__factory_1.OpGasPriceOracleMock__factory; } });
