'use strict';

var promises = require('fs/promises');
var glob = require('glob');
var config_js = require('hardhat/config.js');

const importLineRegex = /^.*from\s+(['"])(\.[^'"]*?)(?<!\.[jt]s|\.json)\1.*$/gm;
config_js.task("typechain:fix", "Fix Typechain definitions for ESM generated by Hardhat").addParam("dir", "Typechain Directory", "").setAction(async (taskArgs, hre) => {
  const dir = taskArgs.dir || hre.config?.typechain?.outDir || "./typechain-types";
  console.log(`typechain:fix: scanning type files from ${dir}`);
  const files = await glob.glob(`${dir}/**/*.ts`, { ignore: "node_modules/**" });
  for (const file of files) {
    let context = await promises.readFile(file, { encoding: "utf8" });
    if (context.match(importLineRegex)) {
      console.log(`typechain:fix: fixed ${file}`);
      context = context.replace(
        /from\s+(['"])(\.[^'"]*?)(?<!\.[jt]s|\.json)\1/g,
        "from$1$2/index.js$1"
      );
    }
    await promises.writeFile(file, context);
  }
});
