import { webcrypto } from 'crypto';
/**
 * Detects (heuristically) whether runtime is Node.js.
 * @returns {boolean} True if running in Node.js, false otherwise (browser).
 */
export declare const isNode: boolean;
/**
 * Computes optimal concurrency and batchSize for a given rate-per-second
 * limit and batch interval (delays), maximizing both under the constraint:
 *   concurrency * batchSize <= ratePerBatch
 *
 * We allow 0 delays to execute batches without delays but the batch size would remain the same
 *
 * @param {number} ratePerSecond - Maximum calls per second allowed.
 * @param {number} [maxBatch=5] - Maximum batch size.
 * @param {number} [delays=1000] - Fixed delay time for each batch (ms).
 * @returns {{ concurrency: number, batchSize: number, delays: number }} An object containing concurrency, batchSize, and delays.
 */
export declare function createBatchRateConfig(ratePerSecond: number, maxBatch?: number, delays?: number): {
    concurrency: number;
    batchSize: number;
    delays: number;
};
/**
 * Creates an array of block tag ranges for batching.
 * @param {number} fromBlock - First block.
 * @param {number} toBlock - Last block.
 * @param {number} [batchSize=1000] - Number of blocks per batch.
 * @param {boolean} [reverse=false] - If true, returns ranges in reverse order.
 * @returns {Array<{fromBlock: number, toBlock: number}>} Array of objects specifying the range for each batch.
 * @throws {Error} If the block range is invalid.
 */
export declare function createBlockTags(fromBlock: number, toBlock: number, batchSize?: number, reverse?: boolean): {
    fromBlock: number;
    toBlock: number;
}[];
/**
 * Generates a range of numbers (inclusive).
 * @param {number} start - First value.
 * @param {number} stop - Last value.
 * @param {number} [step=1] - Increment.
 * @returns {number[]} Array containing the generated range.
 */
export declare function range(start: number, stop: number, step?: number): number[];
/**
 * Splits an array into chunks of a given size.
 * @param {T[]} arr - Array to split.
 * @param {number} size - Maximum size of each chunk.
 * @returns {T[][]} An array of arrays, each with up to 'size' elements.
 * @template T
 */
export declare function chunk<T>(arr: T[], size: number): T[][];
/**
 * Returns a promise resolved after the specified duration.
 * @param {number} ms - Milliseconds to sleep.
 * @returns {Promise<void>} Promise that resolves after the delay.
 */
export declare function sleep(ms: number): Promise<void>;
/**
 * Node/browser-compatible cryptography interface.
 */
export declare const crypto: webcrypto.Crypto;
/**
 * Performs a digest (SHA-256 or other) of a byte array.
 * @param {Uint8Array} bytes - Input bytes.
 * @param {string} [algorithm='SHA-256'] - Algorithm name.
 * @returns {Promise<Uint8Array>} Digest as a Uint8Array.
 */
export declare function digest(bytes: Uint8Array, algorithm?: string): Promise<Uint8Array>;
/**
 * Hashes a hex string to another hex string digest.
 * @param {string} hexStr - Input hex string.
 * @param {string} [algorithm='SHA-256'] - Algorithm to use.
 * @returns {Promise<string>} Hex string (with 0x) of the digest.
 */
export declare function digestHex(hexStr: string, algorithm?: string): Promise<string>;
/**
 * Generates a cryptographically random byte buffer.
 * @param {number} [length=32] - Number of bytes.
 * @returns {Uint8Array} Randomly generated bytes.
 */
export declare function rBytes(length?: number): Uint8Array;
/**
 * Converts Node.js Buffer to Uint8Array.
 * @param {Buffer} b - Node.js Buffer.
 * @returns {Uint8Array} Converted Uint8Array.
 */
export declare function bufferToBytes(b: Buffer): Uint8Array;
/**
 * Concatenates multiple Uint8Arrays into one.
 * @param {...Uint8Array[]} arrays - Arrays to concatenate.
 * @returns {Uint8Array} New concatenated Uint8Array.
 */
export declare function concatBytes(...arrays: Uint8Array[]): Uint8Array;
/**
 * Converts a 0x-prefixed hex string or bigint to a Uint8Array.
 * @param {bigint | string} input - The input hex string or bigint.
 * @returns {Uint8Array} The bytes.
 */
export declare function hexToBytes(input: bigint | string): Uint8Array;
/**
 * Converts a Uint8Array to a 0x-prefixed hex string.
 * @param {Uint8Array} bytes - Input bytes.
 * @returns {string} Hex string of the bytes, 0x-prefixed.
 */
export declare function bytesToHex(bytes: Uint8Array): string;
/**
 * Pads to even-length hex string and ensures 0x prefix.
 * @param {string} hexStr - Hex string with or without prefix.
 * @returns {string} 0x-prefixed, even-length hex string.
 */
export declare function toEvenHex(hexStr: string): string;
/**
 * Converts a bigint/number/string into a 0x-prefixed, fixed-length-zero-padded hex string.
 * @param {bigint | number | string} numberish - The number, bigint, or numeric string.
 * @param {number} [length=32] - Number of bytes in output.
 * @returns {string} Fixed-length, 0x-prefixed hex string.
 */
export declare function toFixedHex(numberish: bigint | number | string, length?: number): string;
/**
 * Base64
 */
/**
 * Converts a base64 string to a Uint8Array.
 * @param {string} base64 - Input base64 string.
 * @returns {Uint8Array} Decoded bytes as a Uint8Array.
 */
export declare function base64ToBytes(base64: string): Uint8Array;
/**
 * Converts bytes to a base64 string.
 * @param {Uint8Array} bytes - Bytes to encode.
 * @returns {string} Base64-encoded string.
 */
export declare function bytesToBase64(bytes: Uint8Array): string;
/**
 * Converts a base64-encoded string to a 0x-prefixed hex string.
 * @param {string} base64 - Base64 string.
 * @returns {string} Hex string representation.
 */
export declare function base64ToHex(base64: string): string;
/**
 * Converts a 0x-prefixed hex string to a base64 string.
 * @param {string} hex - Input hex string, prefixed or not.
 * @returns {string} Base64-encoded version.
 */
export declare function hexToBase64(hex: string): string;
/**
 * Returns true if the string is a valid 0x-prefixed hex representation.
 * @param {string} value - String to check.
 * @returns {boolean} True if valid hex, false otherwise.
 */
export declare function isHex(value: string): boolean;
